config/routes.rb
Mudanzasdelafuente::Application.routes.draw do
  devise_for :users
  #TODO Renombrar rutas
  root to: "home#index"

  resources :material_models do
    collection do
      get :search
    end
  end

  resources :materials do
    collection do
      get :update_shed
      get :search
    end
  end

  resources :location_headquarters
  resources :location_sheds
  resources :shelves

  resources :porterages do
    collection do
      get :search
    end

    member do
      get :deliver
      get :deliver_back
      get :insert_code
      get :scan_code
      put :insert_manual_code
      get :delete_code
      put :insert_batch_codes
    end
  end

end

app/models/porterage.rb
class Porterage < ActiveRecord::Base
  STATUS_TRANSIT = "En transito"
  STATUS_DELIVERED = "Entregado"

  attr_accessible :enter_date, :exit_date, :origin_location, :destiny_location, :status, :operator

  has_many :materials

  belongs_to :origin, class_name: 'Location', foreign_key: :origin_location
  belongs_to :destiny, class_name: 'Location', foreign_key: :destiny_location

  validates_presence_of :origin, :destiny

  before_create :default_values

  def default_values
    self.exit_date = Date.today
    self.status = STATUS_TRANSIT
  end

  searchable do
    integer :id
    text :status
    text :operator

    integer :origin do
      origin.id
    end

    text :materials do
      materials.map { |m| m.material_model.model_type }
    end

    integer :destiny do
      destiny.id
    end

    date :enter_date
    date :exit_date
  end

  def assign_batch_porterages(materials)
    materials.each do |material|
      material.assign_porterage(self)
    end
  end
end

app/controllers/porterages_controller.rb
require 'will_paginate/array'
class PorteragesController < ApplicationController
  protect_from_forgery
  load_and_authorize_resource

  def index
    res = Porterage.search do
      with :id, params[:code] unless params[:code].blank?
      with(:exit_date).greater_than_or_equal_to(params[:day_from].to_date) unless params[:day_from].blank?
      with(:exit_date).less_than_or_equal_to(params[:day_to].to_date) unless params[:day_to].blank?
      with :origin, params[:origin] unless params[:origin].blank?
      with :destiny, params[:destiny] unless params[:destiny].blank?
      keywords params[:model_name] unless params[:model_name].blank?
      fulltext(params[:status])

      paginate per_page: 2000
    end

    @porterages = res.results.paginate(page: params[:page], per_page: Mudanzasdelafuente::Application::ELEMENTS_PER_PAGE)
    @porterages_count = res.results.count

    respond_to do |format|
      format.html
      format.json { render json: @porterages }
    end
  end

  def show
    @porterage = Porterage.find(params[:id])
    @materials = @porterage.materials

    respond_to do |format|
      format.html
      format.json { render json: @porterage }
    end
  end

  def new
    @porterage = Porterage.new

    respond_to do |format|
      format.html
      format.json { render json: @location_shed }
    end
  end

  def create
    @porterage.attributes = params[:porterage]

    respond_to do |format|
      if @porterage.save
        format.html { redirect_to scan_code_porterage_path(@porterage), notice: "Porte creado correctamente" }
        format.json { render json: @porterage, status: :created, location: @porterage }
      else
        format.html { render action: 'new' }
        format.json { render json: @porterage.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @porterage = Porterage.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @porterage }
    end
  end

  def update
    @porterage = Porterage.find(params[:id])

    respond_to do |format|
      if @location_shed.update_attributes(params[:porterage])
        format.html { render 'index', notice: "Porte Modificado Correctamente" }
        format.json { render json: @porterage, status: :ok }
      else
        format.html { render action: 'edit' }
        format.json { render json: @porterage.errors, status: :unprocessable_entity }
      end
    end
  end

  def search
    res = Porterage.search do
      with :id, params[:code] unless params[:code].blank?
      with(:exit_date).greater_than_or_equal_to(params[:day_from].to_date) unless params[:day_from].blank?
      with(:exit_date).less_than_or_equal_to(params[:day_to].to_date) unless params[:day_to].blank?
      with :origin, params[:origin] unless params[:origin].blank?
      with :destiny, params[:destiny] unless params[:destiny].blank?
      fulltext :model_name unless params[:model_name].blank?
      fulltext(params[:status])

      paginate per_page: 2000
    end

    @porterages = res.results
  end

  def scan_code
    @porterage = Porterage.find(params[:id])
    @material_codes = @porterage.materials

    respond_to do |format|
      format.html
      format.json { render json: @porterage }
    end
  end

  def insert_code
    @porterage = Porterage.find(params[:id])
    material = Material.where("id = #{params[:ean][0..-2].to_i}").first
    material.assign_porterage(@porterage)

    respond_to do |format|
      if material.present?
        format.html { redirect_to scan_code_porterage_path(@porterage), notice: "Material asignado al porte" }
      else
        format.html { render action: 'scan_code', alert: "Hubo un error al asignar el material" }
      end
    end
  end

  def insert_manual_code
    @porterage = Porterage.find(params[:id])
    code = params[:qr].split("-")
    material = Material.where("id = #{code[1].to_i}").first
    @material_codes = @porterage.materials

    respond_to do |format|
      if !material.blank? && material.assign_porterage(@porterage)
        format.html { redirect_to scan_code_porterage_path(@porterage), notice: "Material asignado al porte" }
      else
        format.html { redirect_to scan_code_porterage_path(@porterage), alert: "Hubo un error al asignar el material" }
      end
    end
  end

  def insert_batch_codes
    #TODO limpiar digito de control en carga por bloque
    @porterage = Porterage.find(params[:id])
    codes = Material.limpiar_batch(params[:codegroup])
    materials = Material.where("id in(?)", codes.map { |s| s.to_i })

    @porterage.assign_batch_porterages(materials)

    respond_to do |format|
      format.html { redirect_to scan_code_porterage_path(@porterage), notice: "Material asignado al porte" }
    end
  end

  def delete_code
    porterage = Porterage.find(params[:id])
    material = Material.find(params[:code])

    porterage.materials.delete(material)

    @material_codes = porterage.materials
  end

  def deliver
    @porterage = Porterage.find(params[:id])
    @porterage.update_attribute(:status, Porterage::STATUS_DELIVERED)
    @porterage.update_attribute(:enter_date, Date.today)
    @porterage.materials.each do |material|
      material.assign_porterage(@porterage, "destiny")
    end
  end

  def deliver_back
    @porterage = Porterage.find(params[:id])
    @porterage.update_attribute(:status, Porterage::STATUS_TRANSIT)
    @porterage.update_attribute(:enter_date, nil)
  end
end

app/helpers/porterages_helper.rb
module PorteragesHelper
  def origins
    Location.all.map {|x| [x.name, x.id]}
  end

  def destinies
    Location.all.map {|x| [x.name, x.id]}
  end

  def material_models
    MaterialModel.all.map { |x| [(x.model_type + ' ' + x.characteristics + ' ' + x.description + ' - ' + x.measures) , x.model_type] }
  end
end

app/views/porterages/_buscador.html.erb
<div class="accordion no-print" id="accordion2">
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
        <i class="icon-search icon-white"></i> BUSQUEDA</i>
      </a>
    </div>
    <div id="collapseOne" class="accordion-body collapse">
      <div class="accordion-inner">
        <!-- FORM ACORDEON -->

        <%= form_tag porterages_path, method: :get, class: "form-horizontal" do%>
            <div class="row-fluid">
              <div class="span6">   <!-- A la izquierda -->

                <div class="control-group">
                  <label class="control-label" for="code">Identificador</label>
                  <div class="controls">
                    <%= text_field_tag :code %>
                  </div>
                </div>

                <div class="control-group">
                  <label class="control-label" for="inputStatus">Estado</label>
                  <div class="controls">
                    <%= select_tag :status, options_for_select({ "En transito" => "En transito", "Entregado" => "Entregado" }), prompt: "Todos" %>
                  </div>
                </div>

                <div class="control-group">
                  <label class="control-label" for="code">Creado entre</label>
                  <div class="controls">
                    <%= text_field_tag :day_from, '', class: "input-mini pickDateUI" %> y el <%= text_field_tag :day_to, '', class: "input-mini pickDateUI" %>
                  </div>
                </div>

              </div>

              <div class="span6">   <!-- A la derecha -->

                <div class="control-group">
                  <label class="control-label" for="inputOrigin">Origen</label>
                  <div class="controls">
                    <%= select_tag :origin, options_for_select(origins), prompt: "Todos" %>
                  </div>
                </div>

                <div class="control-group">
                  <label class="control-label" for="inputDestiny">Destino</label>
                  <div class="controls">
                    <%= select_tag :destiny, options_for_select(destinies), prompt: "Todos" %>
                  </div>
                </div>

                <div class="control-group">
                  <label class="control-label" for="inputModel">Que contenga</label>
                  <div class="controls">
                    <%= select_tag :model_name, options_for_select(material_models), prompt: "Todos", class: "input-xlarge" %>
                  </div>
                </div>

            </div>
            <p class="pull-right">
              <button class="btn btn-primary" type="submit">Buscar</button>
              <button class="btn" type="reset">Borrar</button>
            </p>

        <% end %>
        <!-- FIN FORM -->
      </div>
    </div>
  </div>
</div>
  </div>
<!-- FIN ACORDEON -->

app/views/porterages/_form.html.erb
<%= form_for @porterage do |f| %>
    <div class="row-fluid">
      <!-- CAMPOS ORIGEN -->
      <div class="span6">
        <h3>Origen</h3>
        <div class="control-group">
          <div class="controls">
            <%= f.select :origin_location, options_for_select(origins) %>
          </div>
        </div>
      </div>
      <!-- CAMPOS DESTINO -->
      <div class="span6">
        <h3>Destino</h3>
        <div class="control-group">
          <div class="controls">
            <%= f.select :destiny_location, options_for_select(destinies) %>
          </div>
        </div>
      </div>

      <div>
        <div class="control-group">
          <label class="control-label" for="porterage_operator"><strong>Operario</strong></label>
          <div class="controls">
            <%= f.text_field :operator %>
          </div>
        </div>
      </div>

      <% unless params[:action] == 'new' %>
          <!-- TABLAS CON MATERIALES -->
          <%#QUE COÑO ES ESTA MIERDA%>
          <div>
            <table class="table table-hover">
              <thead>
              <tr>
                <th>#</th>
                <th>Nombre</th>
                <th>Estado</th>
              </tr>
              </thead>
              <tbody>
              <tr>
                <td>0</td>
                <td>Tableros Puesto</td>
                <td>Mesas</td>
              </tr>
              <tr>
                <td><input type="text" placeholder="Código de barras"></td>
                <td>Tableros Puesto</td>
                <td>Mesas</td>
              </tr>
            </table>
          </div>
      <% end %>
    </div>
    <div class="form-actions">
      <p class="pull-right">
        <button class="btn btn-primary" type="submit">Crear Porte</button>
        <button class="btn" type="reset">Limpiar</button>
      </p>
    </div>
<% end %>

app/views/porterages/_material.html.erb
<% materials.each do |material| %>
    <tr>
      <td><%= material.id %></td>
      <td><%= material.material_model.model_type %></td>
      <td><%= material.material_model.characteristics %></td>
      <td><%= link_to material.material_model.description, material %></td>
      <td><%= material.status.name %></td>
      <td><%= material.shelf.location_shed.name %> - <%= material.shelf.name %></td>
    </tr>
<% end %>

app/views/porterages/_material_code.html.erb
<% material_codes.each do |material_code| %>
<tr>
  <td><%= material_code.id %></td>
  <td><%= material_code.material_model.model_type %></td>
  <td><%= material_code.material_model.characteristics %></td>
  <td><%= link_to material_code.material_model.description, material_code %></td>
  <td><%= link_to '<i class="icon-trash"></i>'.html_safe, delete_code_porterage_path(@porterage, code: material_code.id), method: :get, remote: true %></td>
</tr>
<% end %>

app/views/porterages/_porterage.html.erb
<tr>
  <td><%= porterage.id %></td>
  <td><%= porterage.origin.name %></td>
  <td><%= porterage.destiny.name %></td>
  <td><%= porterage.exit_date %></td>
  <td id="enter_date_for_<%= porterage.id %>"><%= porterage.enter_date.present? ? porterage.enter_date : "Por definir" %></td>
  <td id="status_for_<%= porterage.id %>"><%= porterage.status %></td>
  <td class="no-print">
    <%= link_to "Ver", porterage_path(porterage), method: :get, class: "btn" %>
    <%= link_to "Scan", scan_code_porterage_path(porterage), class: "btn", method: :get if porterage.status == Porterage::STATUS_TRANSIT%>
  </td>
</tr>

app/views/porterages/change_status.js.erb
$("#status_for_<%= @porterage.id.to_s %>").html("<%= j @porterage.status %>");
$("#enter_date_for_<%= @porterage.id.to_s %>").html("<%= j @porterage.enter_date.to_s %>");

app/views/porterages/delete_code.js.erb
<% if @material_codes.present? %>
$('#materials-table').html("<%= j render partial: "material_code", locals: { material_codes: @material_codes } %>");
<% else %>
$('#materials-table').remove();
<% end %>

app/views/porterages/deliver.js.erb
$('#boton_entregar').fadeOut();
$('#botonera').html("<%= j link_to "<i class=\"icon-road icon-white\"></i> En Transito".html_safe, deliver_back_porterage_path(@porterage), class: "btn btn-warning", id: "boton_entregar_back", remote: true, method: :get %>");
$('#scan_code_button').fadeOut();
$('#porterage_status_small').html("<%= j @porterage.status %>");
$('#fecha_entrega').html("<%= j @porterage.enter_date.to_s %>");

app/views/porterages/deliver_back.js.erb
$('#boton_entregar_back').fadeOut();
$('#botonera').html("<%= j link_to "<i class=\"icon-ok-sign icon-white\"></i> Entregar".html_safe, deliver_porterage_path(@porterage), class: "btn btn-success", id: "boton_entregar", remote: true, method: :get %>");
$('#porterage_status_small').html("<%= j @porterage.status %>");
$('#fecha_entrega').html("Por definir");

app/views/porterages/index.html.erb
<%= render :partial => 'buscador' %>
<div class="row-fluid no-print">
  <div class="span1 offset9">
    <button class="btn visible-desktop" type="button" onClick="window.print()">Imprimir</button>
  </div>
  <div class="span2">
    <%= button_to "Nuevo Porte", new_porterage_path, class: "btn btn-success", type: "button", method: :get  %>
  </div>
</div>
<!-- Inicio Tablas -->
<table class="table table-hover">
  <thead>
  <tr>
    <th>#</th>
    <th>Origen</th>
    <th>Destino</th>
    <th>Fecha Creación</th>
    <th>Fecha Entrega</th>
    <th>Estado</th>
    <th class="no-print">Ops.</th>
  </tr>
  </thead>
  <tbody id="porterages-table">
  <%= render @porterages %>
  </tbody>
</table>

<div class="row-fluid">
  <div class="span5"><%= will_paginate @porterages %></div>
  <div class="span2 offset5" id="porterages_counter"><strong><%= @porterages_count %> resultados</strong></div>
</div>

app/views/porterages/new.html.erb
<h1>Crear porte</h1>
<hr>
<div class="row-fluid">
  <div class="span3 visible-desktop box-info">
    <h4>Hagamos un porte:</h4>
    <ol>
      <li>Debemos de seleccionar el origen y el destino de los materiales que enviemos.</li>
      <li>Identificar los materiales: leyendo el codigo de barras con una cámara móvil, introduciendolo a mano, o bien con una pistola lectora.</li>
      <li>Después de crearlo podremos sacar una copia del albarán para adjuntarla al envío.</li>
    </ol>
    <p>Podremos visualizar todos los portes en el apartado del menu superior <i>Portes</i>.</p>
  </div>
  <div class="span9"><%= render 'form' %></div>
</div>

app/views/porterages/scan_code.html.erb
<div class="row-fluid">
  <div class="span3 visible-desktop box-info">
    <h4>Creando un porte</h4>
    <p>Ahora debemos asociar materiales al porte con el boton "Añadir material".</p>
  </div>
  <div class="span9">

    <h1><%= @porterage.origin.name %> - <%= @porterage.destiny.name %></h1>

    <h1><small><%= @porterage.created_at %></small></h1>
    <hr>


    <%= form_tag insert_manual_code_porterage_path, class: "form-horizontal", id: "form-scancode", method: :put do |f| %>

        <h4>Añadir material a mano...</h4>
        <div class="row-fluid">
          <div class="control-group">
            <label class="control-label" for="qr">Introducir Código</label>
            <div class="controls">
              <%= text_field_tag :qr %>
              <button class="btn btn-primary" type="submit">Buscar</button>
            </div>
          </div>
        </div>

    <% end %>

    <%= form_tag insert_batch_codes_porterage_path, class: "form-horizontal", id: "form-scancode", method: :put do |f| %>
        <div class="visible-desktop">
          <h4>Añadir materiales con la pistola...</h4>
          <div class="row-fluid">
            <div class="control-group">
              <label class="control-label" for="qr">Introducir Códigos</label>
              <div class="controls">
                <%= text_area_tag :codegroup, "", rows: 5 %>
                <button class="btn btn-primary" type="submit">Añadir</button>
              </div>
            </div>
          </div>
        </div>

    <% end %>

    <div class="control-group hidden-desktop">
      <label class="control-label">O escanear con la cámara:</label>
      <div class="controls">
        <%= link_to "Escanear Material", "pic2shop://scan?callback=#{CGI.escape(insert_code_porterage_url(@porterage))}", class: "btn btn-primary" %>
      </div>
    </div>
    </div>

    <table class="table table-hover">
      <thead>
      <th>#</th>
      <th>Material</th>
      <th>Caracteristicas</th>
      <th>Modelo</th>
      <th>Borrar</th>
      </thead>
      <tbody id="materials-table">
      <%= render partial: "material_code", locals: {material_codes: @material_codes} if @material_codes.present? %>
      </tbody>
    </table>

    <div class="pull-right">
      <%= link_to "Volver al porte", porterage_path(@porterage), class: "btn" %>
    </div>

    </div>
  </div>

app/views/porterages/search.js.erb
$('#porterages-table').html("<%= j render @porterages %>");
$('#porterages_counter').html("<%= j @porterages.count.to_s + " resultados" %>");

app/views/porterages/show.html.erb
<h1><%= @porterage.origin.name %> - <%= @porterage.destiny.name %></h1>
<h1><small id="porterage_status_small"><%= @porterage.status %></small></h1>
<hr>

<div class="row-fluid">
  <div class="span3">
    <h4>Fecha de creación</h4>
    <p><%= @porterage.created_at %><p>
  </div>
  <div class="span3">
    <h4>Fecha de entrega</h4>
    <p id="fecha_entrega"><%= @porterage.enter_date.present? ? @porterage.enter_date : "Por definir" %><p>
  </div>
</div>

<h4>Operario</h4>
<p><%= @porterage.operator %><p>

  <!-- Inicio Tablas -->
<table class="table table-hover">
  <thead>
  <tr>
    <th>#</th>
    <th>Material</th>
    <th>Caracteristicas</th>
    <th>Modelo</th>
    <th>Estado</th>
    <th>Procedencia</th>
  </tr>
  </thead>
  <tbody>
  <%= render partial: 'material', locals: {materials: @materials} %>
  </tbody>
</table>
<div class="row-fluid">
  <div class="span2 offset10"><strong><%= @materials.count %> objetos</strong></div>
</div>

<div class="row-fluid no-print form-actions">
  <div class="span1 offset7">
    <button class="btn visible-desktop" type="button" onClick="window.print()">Imprimir</button>
  </div>
  <div class="span2">
    <%= link_to "<i class=\"icon-barcode icon-white\"></i> Añadir material".html_safe, scan_code_porterage_path(@porterage), class: "btn btn-primary", id: "scan_code_button", method: :get if @porterage.status == Porterage::STATUS_TRANSIT %>
  </div>
  <div class="span2" id="botonera">
    <%= link_to "<i class=\"icon-road icon-white\"></i> Entregar".html_safe, deliver_porterage_path(@porterage), class: "btn btn-success", id: "boton_entregar", remote: true, method: :get if @porterage.status == Porterage::STATUS_TRANSIT %>
    <%= link_to "<i class=\"icon-ok-sign icon-white\"></i> Entregado".html_safe, deliver_back_porterage_path(@porterage), class: "btn btn-warning", id: "boton_entregar_back", remote: true, method: :get if @porterage.status == Porterage::STATUS_DELIVERED %>
  </div>
</div>