config/routes.rb
Mudanzasdelafuente::Application.routes.draw do
  devise_for :users
  #TODO Renombrar rutas
  root to: "home#index"

  resources :material_models do
    collection do
      get :search
    end
  end

  resources :materials do
    collection do
      get :update_shed
      get :search
    end
  end

  resources :location_headquarters
  resources :location_sheds
  resources :shelves

  resources :porterages do
    collection do
      get :search
    end

    member do
      get :deliver
      get :deliver_back
      get :insert_code
      get :scan_code
      put :insert_manual_code
      get :delete_code
      put :insert_batch_codes
    end
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.is_illuminadmin?
      can :manage, :all
    else
      # no permissions
    end
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name

  validates_presence_of :name
  validates_uniqueness_of :name

  has_many :material_models
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :porterages
  has_many :materials
  attr_accessible :name, :address, :postal_code, :city, :province, :country
end

app/models/location_headquarter.rb
class LocationHeadquarter < Location
  has_many :material_models

  validates_presence_of :name, :address, :postal_code, :city, :province, :country

end

app/models/location_shed.rb
class LocationShed < Location
  has_many :shelves

  validates_presence_of :name
  validates_uniqueness_of :name
end

app/models/material.rb
class Material < ActiveRecord::Base
  after_create :assign_shelf_location
  require 'barby'
  require 'barby/barcode/code_128'
  require 'barby/barcode/ean_13'
  require 'barby/outputter/png_outputter'
  require 'chunky_png'

  attr_accessible :barcode, :status_id, :category_id, :porterage_id, :shelf_id, :material_model_id, :location_id, :shelf_part, :zone

  belongs_to :porterage
  belongs_to :shelf
  belongs_to :material_model
  belongs_to :location
  belongs_to :status

  validates_uniqueness_of :barcode
  validates_presence_of :location_id

  scope :material_per_location, lambda{ |location_filter| where("location_id = ?", location_filter) }
  scope :material_per_model, lambda{ |model_filter| where("material_model_id = ?", model_filter)}

  #SolR method
  searchable do
    integer :id

    integer :status do
      status.id
    end

    text :shelf do
      shelf.name
    end

    text :location_shed do
      shelf.location_shed.name
    end

    integer :model do
      material_model.id
    end

    integer :location do
      location.id
    end
  end

  def assign_porterage(porterage, type = "origin")
    self.porterage_id = porterage.id
    self.location_id = porterage.origin.id if type == "origin"
    self.location_id = porterage.destiny.id if type == "destiny"
    self.save
  end

  def assign_shelf_location
    self.location_id = self.shelf.location_shed_id
    self.save
  end

  def ean_code
    ceroisimas = 12 - id.to_s.size
    res = id.to_s

    ceroisimas.times do |cero|
      res.insert 0, "0"
    end

    res
  end

  def self.limpiar_batch(batch)
    batch = batch.split("\n")
    res = []
    batch.each do |codigo|
      codigo = codigo.to_i / 10
      res << codigo
    end

    res
  end

  def full_code
    self.material_model.id.to_s + "-" + self.id.to_s
  end

end

app/models/material_model.rb
class MaterialModel < ActiveRecord::Base
  attr_accessible :name, :description, :furniture, :measures, :luggage, :location_headquarter_id,
                  :photo, :photo2, :photo3, :model_type, :characteristics, :color, :unit

  validates_presence_of  :description, :furniture, :measures, :characteristics, :model_type

  has_many :materials, dependent: :destroy
  belongs_to :location_headquarter
  belongs_to :category
  has_attached_file :photo, :styles => { :thumb => "90x90", :large => "400x400"}
  has_attached_file :photo2, :styles => { :thumb => "90x90", :large => "400x400"}
  has_attached_file :photo3, :styles => { :thumb => "90x90", :large => "400x400"}

  #SolR method
  searchable do
    integer :id
    string :name
    string :description
    string :furniture
    text :model_type
    text :characteristics
    text :color
    text :unit

    integer :location_headquarter_id
  end
end

app/models/porterage.rb
class Porterage < ActiveRecord::Base
  STATUS_TRANSIT = "En transito"
  STATUS_DELIVERED = "Entregado"

  attr_accessible :enter_date, :exit_date, :origin_location, :destiny_location, :status, :operator

  has_many :materials

  belongs_to :origin, class_name: 'Location', foreign_key: :origin_location
  belongs_to :destiny, class_name: 'Location', foreign_key: :destiny_location

  validates_presence_of :origin, :destiny

  before_create :default_values

  def default_values
    self.exit_date = Date.today
    self.status = STATUS_TRANSIT
  end

  searchable do
    integer :id
    text :status
    text :operator

    integer :origin do
      origin.id
    end

    text :materials do
      materials.map { |m| m.material_model.model_type }
    end

    integer :destiny do
      destiny.id
    end

    date :enter_date
    date :exit_date
  end

  def assign_batch_porterages(materials)
    materials.each do |material|
      material.assign_porterage(self)
    end
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users
end

app/models/shelf.rb
class Shelf < ActiveRecord::Base
  attr_accessible :name, :location_shed_id

  belongs_to :location_shed

  validates_presence_of :name, :location_shed_id
end

app/models/status.rb
class Status < ActiveRecord::Base
  #ESTA MIERDA NO ES DEFINITIVA
  STATUS_USED = 1
  STATUS_NEW = 2
  STATUS_BROKEN = 3
  STATUS_BAD = 4

  attr_accessible :name

  validates_uniqueness_of :name
  validates_presence_of :name

  has_many :materials
end

app/models/user.rb
class User < ActiveRecord::Base
  #Constantes conspirantes
  ILLUMINADMIN_ROLE = "Illuminadmin"

  # Propiedades de Devise
  devise :database_authenticatable, :rememberable, :trackable, :validatable

  # Atributos manejables desde la aplicación con mass-assignment
  attr_accessible :email, :password, :password_confirmation, :remember_me , :name, :last_name

  # Validaciones de creación de objetos
  validates_uniqueness_of :email
  validates_presence_of :name, :last_name

  has_and_belongs_to_many :roles

  def is_illuminadmin?
    has_role? ILLUMINADMIN_ROLE
  end

  private

  def has_role?(role)
    return !!self.roles.find_by_name(role.to_s.camelize)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  protect_from_forgery

  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def headquarter_list
    LocationHeadquarter.all
  end

  def shed_list
    LocationShed.all
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
  def models_list
    MaterialModel.all.map { |x| [(x.model_type + ' ' + x.characteristics + ' ' + x.description + ' - ' + x.measures) , x.id] }
  end

  def sheds_list
    LocationShed.all.map { |x| [x.name, x.id] }
  end

  def status_list
    Status.all.map { |x| [x.name, x.id] }
  end

  def model_models
    MaterialModel.all.map { |x| [(x.model_type + ' ' + x.characteristics + ' ' + x.description + ' - ' + x.measures) , x.id] }
  end

  def locations
    Location.all.map { |x| [x.name, x.id] }
  end
end

app/helpers/model_items_helper.rb
module ModelItemsHelper
end

app/helpers/porterages_helper.rb
module PorteragesHelper
  def origins
    Location.all.map {|x| [x.name, x.id]}
  end

  def destinies
    Location.all.map {|x| [x.name, x.id]}
  end

  def material_models
    MaterialModel.all.map { |x| [(x.model_type + ' ' + x.characteristics + ' ' + x.description + ' - ' + x.measures) , x.model_type] }
  end
end

app/helpers/shelves_helper.rb
module ShelvesHelper
  def shed_form_list
    arr = LocationShed.all.map { |x| [x.name, x.id] }
    arr
  end
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mudanzas De la Fuente</title>
  <%= javascript_include_tag 'jquery', 'jquery_ujs', 'jquery-ui-1.10.3.custom.min.js', 'bootstrap', 'porterages', 'materials'  %>
  <%= stylesheet_link_tag    "application", "bootstrap", "bootstrap-responsive", "main", "ui-lightness/jquery-ui.min", :media => "all" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!--[if lt IE 9]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

</head>
<body>


<!-- Inicio Navbar -->
<%= render :partial => 'shared/menu' %>
<!-- Fin Navbar -->


<div class="container">
  <%= render 'shared/errors' %>
  <%= yield %>
</div>

</body>
</html>

app/views/shared/_errors.html.erb
<% if notice.present? %><p id="notice" class="alert alert-success"><%= notice.html_safe %></p><%end%>
<% if alert.present? %><p class="alert alert-error"><%= alert.html_safe %></p><%end%>

app/views/shared/_menu.html.erb
<% if current_user.present? %>
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <%= link_to 'DelaFuente', root_path, class: "brand" %>

          <div class="nav-collapse collapse">
            <ul class="nav">

              <li><a href="<%= root_path %>"><i class="icon-home"></i> Inicio</a></li>

              <!-- Inventario -->
              <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <i class="icon-list-alt"></i> Inventario
                <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><%= link_to 'Cátalogo', material_models_path %></li>
                  <li><%= link_to 'Stock', materials_path%></li>
                </ul>

              </li>

              <!-- Lugares -->
              <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <i class="icon-map-marker"></i> Lugares
                <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li class="dropdown-submenu">
                    <%= link_to 'Sedes', location_headquarters_path %>
                    <ul class="dropdown-menu visible">
                      <% headquarter_list.each do |hq| %>
                          <li><%= link_to hq.name, materials_path(location_filter: hq.id) %></li>
                      <% end %>
                    </ul>
                  </li>

                  <li class="dropdown-submenu">
                    <%= link_to 'Almacenes', location_sheds_path %>
                    <ul class="dropdown-menu">
                      <% shed_list.each do |shed| %>
                          <li><%= link_to shed.name, materials_path(location_filter: shed.id) %></li>
                      <% end %>
                    </ul>
                  </li>

                  <li class="divider"></li>

                  <li><%= link_to 'Estanterias', shelves_path %></li>
                </ul>
              </li>


              <!-- Portes -->
              <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <i class="icon-plane"></i> Portes
                <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li>
                  <li><a href="/porterages/">Listado</a></li>
                  <li><a href="/porterages/new">Nuevo Porte</a></li>
                </ul>
              </li>

              <!-- Buscar -->
              <!--<li><a href="#"><i class="icon-search"></i></a></li>-->

            </ul>

            <ul class="pull-right nav">
              <li><%= link_to "<i class=\"icon-off\"></i> Salir".html_safe, destroy_user_session_path, :method => :delete %></li>
            </ul>

          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
<% end %>