config/routes.rb
Mudanzasdelafuente::Application.routes.draw do
  devise_for :users
  #TODO Renombrar rutas
  root to: "home#index"

  resources :material_models do
    collection do
      get :search
    end
  end

  resources :materials do
    collection do
      get :update_shed
      get :search
    end
  end

  resources :location_headquarters
  resources :location_sheds
  resources :shelves

  resources :porterages do
    collection do
      get :search
    end

    member do
      get :deliver
      get :deliver_back
      get :insert_code
      get :scan_code
      put :insert_manual_code
      get :delete_code
      put :insert_batch_codes
    end
  end

end

app/models/location_headquarter.rb
class LocationHeadquarter < Location
  has_many :material_models

  validates_presence_of :name, :address, :postal_code, :city, :province, :country

end

app/controllers/location_headquarters_controller.rb
class LocationHeadquartersController < ApplicationController
  protect_from_forgery
  load_and_authorize_resource
  require 'will_paginate/array'
  def index
    @location_headquarters = LocationHeadquarter.all.paginate(page: params[:page], per_page: Mudanzasdelafuente::Application::ELEMENTS_PER_PAGE)

    respond_to do |format|
      format.html
      format.json { render json: @location_headquarters }
    end
  end

  def show
    @location_headquarter = LocationHeadquarter.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @location_headquarter }
    end
  end

  def new
    @location_headquarter = LocationHeadquarter.new

    respond_to do |format|
      format.html
      format.json { render json: @location_headquarter }
    end
  end

  def create
    @location_headquarter.attributes = params[:location_headquarter]

    respond_to do |format|
      if @location_headquarter.save
        format.html { redirect_to location_headquarters_path, notice: "Sede dada de alta correctamente" }
        format.json { render json: @location_headquarter, status: :created, location: @location_headquarter }
      else
        format.html { render action: 'new' }
        format.json { render json: @location_headquarter.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @location_headquarter = LocationHeadquarter.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @location_headquarter }
    end
  end

  def update
    @location_headquarter = LocationHeadquarter.find(params[:id])

    respond_to do |format|
      if @location_headquarter.update_attributes(params[:location_headquarter])
        format.html { redirect_to location_headquarters_path, notice: "Sede actualizada correctamente" }
        format.json { render json: @location_headquarter, status: :ok }
      else
        format.html { render action: 'edit' }
        format.json { render json: @location_headquarter.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @location_headquarter = LocationHeadquarter.find(params[:id])
    @location_headquarter.destroy

    respond_to do |format|
      format.html { redirect_to location_headquarters_path, notice: "Sede eliminada correctamente" }
      format.json { head :ok }
    end
  end

end

app/helpers/location_headquarters_helper.rb
module LocationHeadquartersHelper
end

app/views/location_headquarters/_form.html.erb
<div class="row-fluid">
  <div class="span3 visible-desktop box-info">
    <h4>Añadir sedes</h4>
    <p>Añade sedes para poder crear destinos y orígenes en los portes.</p>
    <p>Se cuidadoso rellenando los campos, pues serán los datos que aparezcan en el albarán.</p>
  </div>
  <div class="span9">

    <%= form_for @location_headquarter, html: {class: "form-horizontal"} do |f|%>

        <% if @location_headquarter.errors.any? %>
            <div class="alert alert-error">
              <h4>Error:</h4>
              <ul>
                <% @location_headquarter.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
        <% end %>

        <div class="row-fluid">
          <div class="span6">   <!-- A la izquierda -->

            <div class="control-group">
              <label class="control-label" for="location_headquearter_name">Nombre</label>
              <div class="controls">
                <%= f.text_field :name, placeholder: "Introduce el nombre de la sede..." %>
              </div>
            </div>

            <div class="control-group">
              <label class="control-label" for="location_headquarter_address">Dirección</label>
              <div class="controls">
                <%= f.text_field :address, placeholder: "Calle, número, planta, ..." %>
              </div>
            </div>

            <div class="control-group">
              <label class="control-label" for="location_headquarter_postal_code">Código Postal</label>
              <div class="controls">
                <%= f.text_field :postal_code, placeholder: "280XX" %>
              </div>
            </div>

            <div class="control-group">
              <label class="control-label" for="location_headquarter_city">Ciudad</label>
              <div class="controls">
                <%= f.text_field :city, placeholder: "Introduce una ciudad..." %>
              </div>
            </div>

            <div class="control-group">
              <label class="control-label" for="location_headquarter_province">Provincia</label>
              <div class="controls">
                <%= f.text_field :province %>
              </div>
            </div>

            <div class="control-group">
              <label class="control-label" for="location_headquarter_country">País</label>
              <div class="controls">
                <%= f.text_field :country %>
              </div>
            </div>

          </div>

        </div>
        <div class="form-actions">
          <p class="pull-right">
            <button class="btn btn-primary" type="submit">Guardar</button>
            <button class="btn" type="reset">Borrar</button>
          </p>
        </div>

    <% end %>
    <!-- FIN FORM -->
  </div>

</div>

app/views/location_headquarters/_location_headquarter.html.erb
<tr>
  <td><%= location_headquarter.name %></td>
  <td><%= location_headquarter.address %></td>
  <td><%= location_headquarter.city %></td>
  <td><%= location_headquarter.province %></td>
  <td><%= location_headquarter.country %></td>
  <td><%= link_to '<i class="icon-pencil"></i>'.html_safe, edit_location_headquarter_path(location_headquarter) %> <%= link_to '<i class="icon-trash"></i>'.html_safe, location_headquarter_path(location_headquarter), method: :delete %></td>
</tr>

app/views/location_headquarters/edit.html.erb
<h1>Editar Sede</h1>
<hr>

<%= render 'form' %>

app/views/location_headquarters/index.html.erb
<div class="pull-right">
  <%= button_to "Nueva Sede", new_location_headquarter_path, class: "btn btn-success", type: "button", method: :get  %>
</div>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Dirección</th>
      <th>Ciudad</th>
      <th>Provincia</th>
      <th>País</th>
      <th>Ops.</th>
    </tr>
  </thead>
  <tbody>
    <%= render @location_headquarters %>
  </tbody>
</table>

<%= will_paginate @location_headquarters %>

app/views/location_headquarters/new.html.erb
<h1>Crear Sede</h1>
<hr>

<%= render 'form' %>