config/routes.rb
Mudanzasdelafuente::Application.routes.draw do
  devise_for :users
  #TODO Renombrar rutas
  root to: "home#index"

  resources :material_models do
    collection do
      get :search
    end
  end

  resources :materials do
    collection do
      get :update_shed
      get :search
    end
  end

  resources :location_headquarters
  resources :location_sheds
  resources :shelves

  resources :porterages do
    collection do
      get :search
    end

    member do
      get :deliver
      get :deliver_back
      get :insert_code
      get :scan_code
      put :insert_manual_code
      get :delete_code
      put :insert_batch_codes
    end
  end

end

app/models/material.rb
class Material < ActiveRecord::Base
  after_create :assign_shelf_location
  require 'barby'
  require 'barby/barcode/code_128'
  require 'barby/barcode/ean_13'
  require 'barby/outputter/png_outputter'
  require 'chunky_png'

  attr_accessible :barcode, :status_id, :category_id, :porterage_id, :shelf_id, :material_model_id, :location_id, :shelf_part, :zone

  belongs_to :porterage
  belongs_to :shelf
  belongs_to :material_model
  belongs_to :location
  belongs_to :status

  validates_uniqueness_of :barcode
  validates_presence_of :location_id

  scope :material_per_location, lambda{ |location_filter| where("location_id = ?", location_filter) }
  scope :material_per_model, lambda{ |model_filter| where("material_model_id = ?", model_filter)}

  #SolR method
  searchable do
    integer :id

    integer :status do
      status.id
    end

    text :shelf do
      shelf.name
    end

    text :location_shed do
      shelf.location_shed.name
    end

    integer :model do
      material_model.id
    end

    integer :location do
      location.id
    end
  end

  def assign_porterage(porterage, type = "origin")
    self.porterage_id = porterage.id
    self.location_id = porterage.origin.id if type == "origin"
    self.location_id = porterage.destiny.id if type == "destiny"
    self.save
  end

  def assign_shelf_location
    self.location_id = self.shelf.location_shed_id
    self.save
  end

  def ean_code
    ceroisimas = 12 - id.to_s.size
    res = id.to_s

    ceroisimas.times do |cero|
      res.insert 0, "0"
    end

    res
  end

  def self.limpiar_batch(batch)
    batch = batch.split("\n")
    res = []
    batch.each do |codigo|
      codigo = codigo.to_i / 10
      res << codigo
    end

    res
  end

  def full_code
    self.material_model.id.to_s + "-" + self.id.to_s
  end

end

app/controllers/materials_controller.rb
require 'will_paginate/array'
class MaterialsController < ApplicationController
  protect_from_forgery
  load_and_authorize_resource

  def index

    if params[:location_filter].present?
      @materials = Material.material_per_location(params[:location_filter]).paginate(page: params[:page], per_page: Mudanzasdelafuente::Application::ELEMENTS_PER_PAGE)
      @materials_count = Material.material_per_location(params[:location_filter]).count
    elsif params[:model_filter].present?
      @materials = Material.material_per_model(params[:model_filter]).paginate(page: params[:page], per_page: Mudanzasdelafuente::Application::ELEMENTS_PER_PAGE)
      @materials_count = Material.material_per_model(params[:model_filter]).count
    else
      res = Material.search do
        with :id, params[:code] unless params[:code].blank?
        with :status, params[:status] unless params[:status].blank?
        with :model, params[:material_model_name] unless params[:material_model_name].blank?
        with :location, params[:location_name] unless params[:location_name].blank?
        fulltext [params[:shelf], params[:location_shed]].join(" ") unless params[:shelf].blank?
        paginate per_page: 2000
      end

      @materials = res.results.paginate(page: params[:page], per_page: Mudanzasdelafuente::Application::ELEMENTS_PER_PAGE)
      @materials_count = res.results.count
    end


    respond_to do |format|
      format.html
      format.json { render json: @materials }
    end
  end

  def show
    @material = Material.find(params[:id])
    @barcode = Barby::EAN13.new(@material.ean_code)
    p @barcode.inspect
    @blob = Barby::PngOutputter.new(@barcode).to_png #Raw PNG data
    File.open("public/barcodes/#{@material.id}.png", 'w'){|f| f.write @blob }
  end

  def new
    @material = Material.new
    @shelves = []

    respond_to do |format|
      format.html
      format.json { render json: @material }
      format.js
    end
  end

  def create
    number_of_materials = params[:times].to_i

    number_of_materials.times do |material|
      Material.create(params[:material])
    end

    respond_to do |format|
        format.html { redirect_to materials_path, notice: "Material creado correctamente" }
        format.json { render json: @material, status: :created, location: @material }
    end
  end

  def edit
    @material = Material.find(params[:id])
    @shelves = [[@material.shelf.name, @material.shelf.id]]

    respond_to do |format|
      format.html {}
      format.json { render json: @material }
    end

  end

  def update
    @material = Material.find(params[:id])

    respond_to do |format|
      if @material.update_attributes(params[:material])
        format.html { redirect_to materials_path, notice: "Material modificado correctamente" }
        format.json { render json: @material, status: :ok }
      else
        format.html { render action: 'edit' }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @material = Material.find(params[:id])
    @material.destroy

    respond_to do |format|
      format.html { redirect_to materials_path, notice: "Material destruido correctamente" }
      format.json { head :ok }
    end
  end

  def update_shed
    @shelves =  params[:shed_id].present? ? Shelf.where("location_shed_id = #{params[:shed_id]}") : []
    @shelves = @shelves.map { |x| [x.name, x.id] }.insert(0, "Selecciona Estanteria")
  end

  def scancode
    respond_to do |format|
      format.js
    end
  end

  def search
    res = Material.search do
      with :id, params[:code] unless params[:code].blank?
      with :status, params[:status] unless params[:status].blank?
      with :model, params[:material_model_name] unless params[:material_model_name].blank?
      with :location, params[:location_name] unless params[:location_name].blank?
      fulltext [params[:shelf], params[:location_shed]].join(" ") unless params[:shelf].blank?
      paginate per_page: 2000
    end

    @materials = res.results.paginate(page: params[:page], per_page: Mudanzasdelafuente::Application::ELEMENTS_PER_PAGE)
    @materials_count = res.results.count
  end

end

app/helpers/materials_helper.rb
module MaterialsHelper
  def models_list
    MaterialModel.all.map { |x| [(x.model_type + ' ' + x.characteristics + ' ' + x.description + ' - ' + x.measures) , x.id] }
  end

  def sheds_list
    LocationShed.all.map { |x| [x.name, x.id] }
  end

  def status_list
    Status.all.map { |x| [x.name, x.id] }
  end

  def model_models
    MaterialModel.all.map { |x| [(x.model_type + ' ' + x.characteristics + ' ' + x.description + ' - ' + x.measures) , x.id] }
  end

  def locations
    Location.all.map { |x| [x.name, x.id] }
  end
end

app/views/materials/_buscador.html.erb
<div class="accordion" id="accordion2">
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
        <i class="icon-search icon-white"></i> BUSQUEDA</i>
      </a>
    </div>
    <div id="collapseOne" class="accordion-body collapse">
      <div class="accordion-inner">
        <!-- FORM ACORDEON -->
        <%= form_tag materials_path, class: "form-horizontal", method: :get do %>
            <div class="row-fluid">
              <div class="span6">   <!-- A la izquierda -->

                <div class="control-group">
                  <label class="control-label" for="code">Código</label>
                  <div class="controls">
                    <%= text_field_tag :code %>
                  </div>
                </div>

                <div class="control-group">
                  <label class="control-label" for="inputShelf">Estanteria</label>
                  <div class="controls">
                    <%= text_field_tag :shelf %>
                  </div>
                </div>

                <div class="control-group">
                  <label class="control-label" for="inputLocation">Ubicación</label>
                  <div class="controls">
                    <%= select_tag :location_name, options_for_select(locations), prompt: "Todos" %>
                  </div>
                </div>

              </div>

              <div class="span6">   <!-- A la derecha -->
                <div class="control-group">
                  <label class="control-label" for="inputModel">Material de</label>
                  <div class="controls">
                    <%= select_tag :material_model_name, options_for_select(model_models), prompt: "Todos" %>
                  </div>
                </div>

                <div class="control-group">
                  <label class="control-label" for="inputStatus">Estado</label>
                  <div class="controls">
                    <%= select_tag :status, options_for_select(status_list), prompt: "Todos" %>
                  </div>
                </div>

              </div>
            </div>
            <p class="pull-right">
              <button class="btn btn-primary" type="submit">Buscar</button>
              <button class="btn" type="reset">Borrar</button>
            </p>

        <% end %>
        <!-- FIN FORM -->
      </div>
    </div>
  </div>
</div>
<!-- FIN ACORDEON -->

app/views/materials/_form.html.erb
<div class="row-fluid">
  <div class="span3 visible-desktop box-info">
    <h4>Y ahora...</h4>
    <p>Con nuestro catalogo de modelos hecho, ya podemos añadir la cantidad de Stock que tenemos de cada material, y <strong>donde</strong> lo tenemos almacenado.</p>
    <p>Una vez terminado esto podemos empezar a realizar portes.</p>
  </div>
  <div class="span9">

    <%= form_for @material, class: "form-horizontal" do |f| %>

        <% if @material.errors.any? %>
            <div class="alert alert-error">
              <h4>Error:</h4>
              <ul>
                <% @material.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
        <% end %>

        <div class="row-fluid">
          <div class="span6">   <!-- A la izquierda -->

            <div class="control-group">
              <label class="control-label" for="inputModel">Material</label>
              <div class="controls">
                <%= f.select :material_model_id, models_list  %>
              </div>
            </div>

            <div class="control-group">
              <label class="control-label" for="inputShed">Almacén</label>
              <div class="controls">
                <%= f.select :location_id, options_for_select(sheds_list) , prompt: "Selecciona almacén", id: "shedSelect" %>
              </div>
            </div>

            <div class="control-group">
              <label class="control-label" for="inputShelf">Estanteria</label>
              <div class="controls">
                <%= f.select :shelf_id, @shelves, prompt: "Selecciona Estanteria" %>
              </div>
            </div>

            <div class="control-group">
              <label class="control-label" for="inputShelf_part">Balda</label>
              <div class="controls">
                <%= f.text_field :shelf_part, value: "NULO" %>
              </div>
            </div>

            <div class="control-group">
              <label class="control-label" for="inputZone">Zona</label>
              <div class="controls">
                <%= f.text_field :zone, value: "NULO" %>
              </div>
            </div>

            <div class="control-group">
              <label class="control-label" for="material_status_id">Estado</label>
              <div class="controls">
                <%= f.select :status_id, Status.all.collect {|s| [s.name, s.id]}  %>
              </div>
            </div>

            <% if action_name == "new" %>
                <div class="control-group">
                  <label class="control-label" for="material_status_id">¿Cuántos añadir?</label>
                  <div class="controls">
                    <%= text_field_tag :times, 1 %>
                  </div>
                </div>
            <% end %>
          </div>

        </div>
        <div class="form-actions">
          <p class="pull-right">
            <button class="btn btn-primary" type="submit">Guardar</button>
            <button class="btn" type="reset">Borrar</button>
          </p>
        </div>

    <% end %>
    <!-- FIN FORM -->
  </div>

</div>

app/views/materials/_form_edit.html.erb
<div class="row-fluid">
  <div class="span3 visible-desktop box-info">
    <h4>Y ahora...</h4>
    <p>Con nuestro catalogo de modelos hecho, ya podemos añadir la cantidad de Stock que tenemos de cada material, y <strong>donde</strong> lo tenemos almacenado.</p>
    <p>Una vez terminado esto podemos empezar a realizar portes.</p>
  </div>
  <div class="span9">

    <%= form_for @material, class: "form-horizontal" do |f| %>

        <% if @material.errors.any? %>
            <div class="alert alert-error">
              <h4>Error:</h4>
              <ul>
                <% @material.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
        <% end %>


        <div class="row-fluid">

          <div class="span4">
            <h4>Código</h4>
            <p><%= @material.full_code %><p>

            <h4>Características</h4>
            <p><%= @material.material_model.model_type %></p>

            <h4>Modelo</h4>
            <p><%= f.select :material_model_id, models_list  %><p>

            <h4>Categoria</h4>
            <p><%= @material.material_model.furniture %></p>

            <h4>Procedencia</h4>
            <p><%= @material.material_model.location_headquarter.name rescue nil %></p>

            <h4>Estado</h4>
            <p><%= f.select :status_id, options_for_select(status_list) %><p>

            <h4>Fecha</h4>
            <p><%= @material.created_at %></p>

          </div>

          <div class="span4">

            <h4>Medidas <small>(CM AL/AN/PF)</small></h4>
            <p><%= @material.material_model.measures %></p>

            <h4>Color</h4>
            <p><%= @material.material_model.color %></p>

            <h4>Ubicación Actual</h4>
            <p><%= f.select :location_id, options_for_select(sheds_list) , prompt: "Selecciona almacén", id: "shedSelect" %></p>

            <h4>Estantería</h4>
            <p><%= f.select :shelf_id, @shelves, prompt: "Selecciona Estanteria" %></p>

            <h4>Balda</h4>
            <p><%= f.text_field :shelf_part %></p>

            <h4>Zona</h4>
            <p><%= f.text_field :zone %></p>
          </div>

        </div>

        <div class="form-actions">
          <p class="pull-right">
            <button class="btn btn-primary" type="submit">Guardar</button>
            <button class="btn" type="reset">Borrar</button>
          </p>
        </div>

    <% end %>
    <!-- FIN FORM -->
  </div>

</div>

app/views/materials/_material.html.erb
<tr>
  <td><%= material.full_code %></td>
  <td><%= link_to material.material_model.model_type, material_path(material) %></td>
  <td><%= material.material_model.characteristics %></td>
  <td><%= material.material_model.description %></td>
  <td><%= material.material_model.furniture %></td>
  <td><%= material.material_model.measures %></td>
  <td><%= material.status.name %></td>
  <td><%= material.location.name || material.shelf.location_shed.name rescue nil%></td>
</tr>

app/views/materials/edit.html.erb
<h1>Editar material</h1>
<hr>

<%= render 'form_edit' %>

app/views/materials/index.html.erb
<%= render :partial => 'buscador' %>

<div class="row-fluid">
  <div class="span2" id="materials_counter"><strong><%= @materials_count %> Resultados</strong></div>
  <div class="span2 offset8">
    <%= button_to "Crear Stock de Material", new_material_path, class: "btn btn-success", type: "button", method: :get  %>
  </div>
</div>

<!-- Inicio Tablas -->
<table class="table table-hover">
  <thead>
  <tr>
    <th>#</th>
    <th>Material</th>
    <th>Características</th>
    <th>Modelo</th>
    <th>Categoria</th>
    <th>Medidas</th>
    <th>Estado</th>
    <th>Ubicación</th>
  </tr>
  </thead>
  <tbody>
  <%= render @materials %>
  </tbody>
</table>

<div class="row-fluid">
  <div class="span5"><%= will_paginate @materials %></div>
</div>

app/views/materials/new.html.erb
<h1>Crear Stock de modelo</h1>
<hr>

<%= render 'form' %>

app/views/materials/search.js.erb
$("tbody").html("<%= j render @materials %>");
$("#materials_counter").html("<%= j @materials_count.to_s + " resultados" %>");

app/views/materials/show.html.erb
<h1><%= @material.material_model.model_type %> <%= @material.material_model.characteristics %> <%= @material.material_model.description %></h1>
<hr>

<div class="row-fluid">

  <!-- QR CODE -->
  <div class="span4">
    <div><%= image_tag "/barcodes/#{@material.id}.png", id: "barcode" %>
      <div style="width: 115px; text-align: center;"><%= @material.full_code %></div>
    </div>
    <!--<img id="barcode" src="http://chart.apis.google.com/chart?cht=qr&chs=300x300&chl=<%= @material.id %>&chld=H|0" />-->
  </div>

  <div class="span8">
    <div class="span4">
      <h4>Código</h4>
      <p><%= @material.full_code %><p>

      <h4>Características</h4>
      <p><%= @material.material_model.model_type %></p>

      <h4>Modelo</h4>
      <p><%= link_to @material.material_model.description, material_model_path(@material.material_model) %><p>

      <h4>Categoria</h4>
      <p><%= @material.material_model.furniture %></p>

      <h4>Procedencia</h4>
      <p><%= @material.material_model.location_headquarter.name rescue nil %></p>

      <h4>Estado</h4>
      <p><%= @material.status.name %><p>

      <h4>Fecha</h4>
      <p><%= @material.created_at %></p>

    </div>

    <div class="span4">

      <h4>Medidas <small>(CM AL/AN/PF)</small></h4>
      <p><%= @material.material_model.measures %></p>

      <h4>Color</h4>
      <p><%= @material.material_model.color %></p>

      <h4>Ubicación Actual</h4>
      <p><%= @material.location.name || @material.shelf.location_shed.name %></p>

      <h4>Estantería</h4>
      <p><%= @material.shelf.name %></p>

      <h4>Balda</h4>
      <p><%= @material.shelf_part %></p>

      <h4>Zona</h4>
      <p><%= @material.zone %></p>
    </div>

  </div>

</div>


<div class="row-fluid no-print form-actions">
  <div class="span1 offset6">
    <button class="btn visible-desktop" type="button" onClick="window.print()">Imprimir</button>
  </div>
  <div class="span2">
    <a href="<%= "/barcodes/#{@material.id}.png" %>" class="btn">Imprimir Código</a>
  </div>
  <div class="span1">
    <%= link_to "Editar", edit_material_path(@material), class: "btn" %>
  </div>
  <div class="span2">
    <%= button_to "Borrar", material_path, class: "btn btn-danger", type: "button", method: :delete %>
  </div>
</div>

app/views/materials/update_shed.js.erb
$('#material_shelf_id').html("<%= escape_javascript(options_for_select(@shelves)) %>")